server:
  port: 8080

jwt:
  secret: OJLJzlvWjstALHdGyoW7mBdlmqTX71ow0gK8aPzeX28=

spring:
  config:
    import:
      - optional:file:.env.properties

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: collinsxzibit1?
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 86037387988-1v9p2n7om7urtpdmksfev0op7e26ddfe.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            client-name: google
            redirect-uri: {baseUrl}/login/oauth2/code/{registrationId}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: email